#ifdef USE_WINNT
    #include <windows.h>
    #include <winnt.h>
#else

#ifndef __WIN_HEADERS__
#define __WIN_HEADERS__

#include "win_types.h"

#define IMAGE_DOS_SIGNATURE S_DOS
#define IMAGE_NT_SIGNATURE S_NT

#define IMAGE_NT_OPTIONAL_HDR32_MAGIC	OH_NT32
#define IMAGE_NT_OPTIONAL_HDR64_MAGIC	OH_NT64
#define IMAGE_ROM_OPTIONAL_HDR_MAGIC	OH_ROM
#define IMAGE_DOS_HEADER IMG_DOS_HEADER

/* data directory */
#define IMAGE_NUMBEROF_DIRECTORY_ENTRIES    DIRECTORY_ENTRIES_NUM
#define IMAGE_DIRECTORY_ENTRY_EXPORT	    DIR_EXPORT
#define IMAGE_DIRECTORY_ENTRY_IMPORT	    DIR_IMPORT

/* section flags */
#define IMAGE_SCN_LNK_NRELOC_OVFL   SCN_LNK_NRELOC_OVFL
#define IMAGE_SCN_MEM_DISCARDABLE   SCN_MEM_DISCARDABLE
#define IMAGE_SCN_MEM_NOT_CACHED    SCN_MEM_NOT_CACHED
#define IMAGE_SCN_MEM_NOT_PAGED	    SCN_MEM_NOT_PAGED
#define IMAGE_SCN_MEM_SHARED	    SCN_MEM_SHARED
#define IMAGE_SCN_CNT_CODE	    SCN_CNT_CODE
#define IMAGE_SCN_MEM_READ	    SCN_MEM_READ
#define IMAGE_SCN_MEM_WRITE	    SCN_MEM_WRITE
#define IMAGE_SCN_MEM_EXECUTE	    SCN_MEM_EXECUTE
#define IMAGE_SCN_CNT_INITIALIZED_DATA	    SCN_CNT_INITIALIZED_DATA
#define IMAGE_SCN_CNT_UNINITIALIZED_DATA    SCN_CNT_UNINITIALIZED_DATA

#define IMAGE_FILE_RELOCS_STRIPPED	F_RELOCS_STRIPPED
#define IMAGE_FILE_EXECUTABLE_IMAGE	F_EXECUTABLE_IMAGE
#define IMAGE_FILE_LINE_NUMS_STRIPPED	F_LINE_NUMS_STRIPPED
#define IMAGE_FILE_LOCAL_SYMS_STRIPPED	F_LOCAL_SYMS_STRIPPED
#define IMAGE_FILE_AGGRESIVE_WS_TRIM	F_AGGRESIVE_WS_TRIM
#define IMAGE_FILE_LARGE_ADDRESS_AWARE	F_LARGE_ADDRESS_AWARE
#define IMAGE_FILE_BYTES_REVERSED_LO	F_BYTES_REVERSED_LO
#define IMAGE_FILE_32BIT_MACHINE	F_MACHINE_32BIT
#define IMAGE_FILE_DEBUG_STRIPPED	F_DEBUG_STRIPPED
#define IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP F_REMOVABLE_RUN_FROM_SWAP
#define IMAGE_FILE_NET_RUN_FROM_SWAP	F_NET_RUN_FROM_SWAP
#define IMAGE_FILE_SYSTEM		F_SYSTEM
#define IMAGE_FILE_DLL			F_DLL
#define IMAGE_FILE_UP_SYSTEM_ONLY	F_UP_SYSTEM_ONLY
#define IMAGE_FILE_BYTES_REVERSED_HI	F_BYTES_REVERSED_HI

#define IMAGE_FILE_MACHINE_UNKNOWN  M_UNKNOWN
#define IMAGE_FILE_MACHINE_I386	    M_I386
#define IMAGE_FILE_MACHINE_R3000    M_R3000 
#define IMAGE_FILE_MACHINE_R4000    M_R4000
#define IMAGE_FILE_MACHINE_R10000   M_R10000
#define IMAGE_FILE_MACHINE_WCEMIPSV2	M_WCEMIPSV2
#define IMAGE_FILE_MACHINE_ALPHA    M_ALPHA
#define IMAGE_FILE_MACHINE_SH3	    M_SH3
#define IMAGE_FILE_MACHINE_SH3DSP   M_SH3DSP
#define IMAGE_FILE_MACHINE_SH3E	    M_SH3E
#define IMAGE_FILE_MACHINE_SH4	    M_SH4
#define IMAGE_FILE_MACHINE_SH5	    M_SH5
#define IMAGE_FILE_MACHINE_ARM	    M_ARM
#define IMAGE_FILE_MACHINE_THUMB    M_THUMB
#define IMAGE_FILE_MACHINE_AM33	    M_AM33
#define IMAGE_FILE_MACHINE_POWERPC  M_POWERPC
#define IMAGE_FILE_MACHINE_POWERPCFP	M_POWERPCFP
#define IMAGE_FILE_MACHINE_IA64	    M_IA64
#define IMAGE_FILE_MACHINE_MIPS16   M_MIPS16
#define IMAGE_FILE_MACHINE_ALPHA64  M_ALPHA64
#define IMAGE_FILE_MACHINE_MIPSFPU  M_MIPSFPU
#define IMAGE_FILE_MACHINE_MIPSFPU16 M_MIPSFPU16
#define IMAGE_FILE_MACHINE_AXP64    M_AXP64
#define IMAGE_FILE_MACHINE_TRICORE M_TRICORE
#define IMAGE_FILE_MACHINE_CEF	    M_CEF
#define IMAGE_FILE_MACHINE_EBC	    M_EBC
#define IMAGE_FILE_MACHINE_AMD64    M_AMD64
#define IMAGE_FILE_MACHINE_M32R	    M_M32R
#define IMAGE_FILE_MACHINE_CEE	    M_CEE

#define IMAGE_SUBSYSTEM_UNKNOWN			    SUB_UNKNOWN
#define IMAGE_SUBSYSTEM_NATIVE			    SUB_NATIVE
#define IMAGE_SUBSYSTEM_WINDOWS_GUI		    SUB_WINDOWS_GUI
#define IMAGE_SUBSYSTEM_WINDOWS_CUI		    SUB_WINDOWS_CUI
#define IMAGE_SUBSYSTEM_OS2_CUI			    SUB_OS2_CUI
#define IMAGE_SUBSYSTEM_POSIX_CUI		    SUB_POSIX_CUI
#define IMAGE_SUBSYSTEM_NATIVE_WINDOWS		    SUB_NATIVE_WINDOWS
#define IMAGE_SUBSYSTEM_WINDOWS_CE_GUI		    SUB_WINDOWS_CE_GUI
#define IMAGE_SUBSYSTEM_EFI_APPLICATION		    SUB_EFI_APPLICATION
#define IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER	    SUB_EFI_BOOT_SERVICE_DRIVER
#define IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER	    SUB_EFI_RUNTIME_DRIVER
#define IMAGE_SUBSYSTEM_EFI_ROM			    SUB_EFI_ROM
#define IMAGE_SUBSYSTEM_XBOX			    SUB_XBOX
#define IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION    SUB_WINDOWS_BOOT_APP

#define IMAGE_ORDINAL_FLAG64 ORDINAL_FLAG64
#define IMAGE_ORDINAL_FLAG32 ORDINAL_FLAG32

#define IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE	    DLL_DYNAMIC_BASE
#define IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY    DLL_FORCE_INTEGRITY
#define IMAGE_DLLCHARACTERISTICS_NX_COMPAT	    DLL_NX_COMPAT
#define IMAGE_DLLCHARACTERISTICS_NO_ISOLATION	    DLL_NO_ISOLATION
#define IMAGE_DLLCHARACTERISTICS_NO_SEH		    DLL_NO_SEH
#define IMAGE_DLLCHARACTERISTICS_NO_BIND	    DLL_NO_BIND
#define IMAGE_DLLCHARACTERISTICS_WDM_DRIVER	    DLL_WDM_DRIVER
#define IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE	DLL_TERMINAL_SERVER_AWARE

#endif /* __WIN_HEADERS__*/
#endif /* #ifndef USE_WINNT */
